<?php
$data_json=file_get_contents("../data.json");
$data=json_decode($data_json, true);

$titre=$data['titre'];
$present=$data['presentataion'];
$mr=$data['etatCivil']['civilite'];
$no=$data['etatCivil']['nom'];
$prenoms=$data['etatCivil']['prenoms'];
$dat=$data['etatCivil']['date2naissance'];
$lie=$data['etatCivil']['lieu2naissance'];
$nation=$data['etatCivil']['nationalite'];
$situation=$data['etatCivil']['situationMatrimoniale'];
$nce=$data['etatCivil']['nce'];
$contact1=$data['etatCivil']['contacts']['mobile'];
$contact2=$data['etatCivil']['contacts']['email'];
$contact3=$data['etatCivil']['contacts']['Google'];
$cursus0=$data['cursusScolaire']['2021-2022']['ecole'];
$diplo0=$data['cursusScolaire']['2021-2022']['diplome'];
$cursus1=$data['cursusScolaire']['2017-2018']['ecole'];
$diplo1=$data['cursusScolaire']['2017-2018']['diplome'];
$cursus2=$data['cursusScolaire']['2010-2011']['ecole'];
$diplo2=$data['cursusScolaire']['2010-2011']['diplome'];
$competence1=$data['Competences']['Informatique']['1'];
$competence2=$data['Competences']['Informatique']['2'];
$competence3=$data['Competences']['Informatique']['3'];
$langue1=$data['Competences']['Langue']['1'];
$langue2=$data['Competences']['Langue']['2'];
$loisir1=$data['Loisirs']['1'];
$loisir2=$data['Loisirs']['2'];
$projet=$data['projet']['groupe']['chef'];
$projet=$data['projet']['dossier'];
$projet=$data['TP']['tp1'];
$projet=$data['TP']['tp2'];
$projet=$data['TP']['tp3'];
$perso=$data['1']['titre']['dossier'];
$perso=$data['2']['titre']['dossier'];
?>
